services:
  postgres:
    image: postgres:17-alpine
    container_name: quiz_postgres
    environment:
      POSTGRES_DB: quiz_db
      POSTGRES_USER: quiz_user
      POSTGRES_PASSWORD: quiz_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:8.0
    container_name: quiz_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # Serwis tylko do seed'owania bazy
  db-seeder:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    environment:
      DATABASE_URL: postgresql://quiz_user:quiz_password@postgres:5432/quiz_db
    depends_on:
      - postgres
    command: >
      sh -c "
        npx prisma db push &&
        npx prisma db seed
      "
    profiles:
      - seed

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: quiz_user_service
    environment:
      DATABASE_URL: postgresql://quiz_user:quiz_password@postgres:5432/quiz_db
      JWT_SECRET: super-secret-jwt-token
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  quiz-service:
    build:
      context: .
      dockerfile: quiz-service/Dockerfile
    container_name: quiz_quiz_service
    environment:
      DATABASE_URL: postgresql://quiz_user:quiz_password@postgres:5432/quiz_db
      PORT: 3002
      USER_SERVICE_URL: http://user-service:3001
    ports:
      - "3002:3002"
    depends_on:
      - postgres
      - user-service

  analytics-service:
    build:
      context: .
      dockerfile: analytics-service/Dockerfile
    container_name: quiz_analytics_service
    environment:
      DATABASE_URL: postgresql://quiz_user:quiz_password@postgres:5432/quiz_db
      MONGODB_URL: mongodb://mongo_user:mongo_password@mongodb:27017/quiz_analytics?authSource=admin
      PORT: 3003
      USER_SERVICE_URL: http://user-service:3001
    ports:
      - "3003:3003"
    depends_on:
      - postgres
      - mongodb
      - user-service

volumes:
  postgres_data:
  mongodb_data: